### ISSUE TITLE
Add instruction about how to config the linter in .eslintrc.js

### ISSUE THREAD

**Issue by kewei-ma** [google/eslint-closure#1]
Could you add some instructions in the README file to illustrate how to config this with eslint? 

Thanks!

**Comment by kewei-ma** [comment]
After I added
`
    "eslint-closure": "^0.0.1",
    "eslint-plugin-closure": "^0.0.1",
    "eslint-config-closure-base": "^0.0.1",
    "eslint-config-closure-es5": "^0.0.1",
    "eslint-config-closure-es6": "^0.0.1"
`
into package.json and did npm install. When I do npm run lint, it says:
`
Cannot find module './dist/closure-eslint-plugin'
Error: Cannot find module './dist/closure-eslint-plugin'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/xxx/xxx/node_modules/eslint-plugin-closure/index.js:15:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
`

**Comment by jschaf** [comment]
Oh, that's not good.  I've published v 0.0.2 with the change.
